export const RECEIVE_CONTACTS = 'RECEIVE_CONTACTS';
export const CHANGE_IS_LOADING_DATA = 'CHANGE_IS_LOADING_DATA';
export const CHANGE_FILTER_TAG = 'CHANGE_FILTER_TAG';
export const INPUT_SEARCH_TEXT = 'INPUT_SEARCH_TEXT';
