// Types of ContactList component
export const RECEIVE_CONTACTS = 'RECEIVE_CONTACTS';
export const CHANGE_IS_LOADING_DATA = 'CHANGE_IS_LOADING_DATA';
export const CHANGE_FILTER_TAG = 'CHANGE_FILTER_TAG';
export const INPUT_SEARCH_TEXT = 'INPUT_SEARCH_TEXT';

// Types of AddContact component
export const RECEIVE_CONTACTS_SOURCES = 'RECEIVE_CONTACTS_SOURCES';
export const CHANGE_IS_SENDING_DATA = 'CHANGE_IS_SENDING_DATA';
export const ADD_PHONE_NUMBER = 'ADD_PHONE_NUMBER';
export const ADD_EMAIL_ADDRESS = 'ADD_EMAIL_ADDRESS';
export const RESET_STATE = 'RESET_STATE';
